apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermarket
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: supermarket
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: supermarket
    spec:
      containers:
        - image: docker.io/springcommunity/supermarket:3.2.0
          imagePullPolicy: IfNotPresent
          name: supermarket
          ports:
            - containerPort: 8080
          resources: {}
