apiVersion: v1
kind: Service
metadata:
  name: supermarket
  labels:
    app: supermarket
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"8080":{}}}'
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: supermarket
  # Use LoadBalancer type instead of ClusterIP
  type: LoadBalancer
